main: manu.BetterSleaps.BetterSleaps
version: 1.5.0
name: BetterSleeps

commands:
  sleep:
    description: Ask other players to sleep.
  bettersleep:
    description: Use /bettersleep or /bs to see the plugin commands.
  bs:
    description: Use /bettersleep or /bs to see the plugin commands.
  bed:
    description: Use /bed to teleport to your bed or other's bed, you can also locate them.